### ISSUE TITLE
Improvement of simple search design

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/raeber-website#78]
When you click on the simple search button, the input fiel appears over the icon. Also, the user does not understand that he has to click on the icon again to get to the advanced search.

Thank you and best regards,
Jan

**Comment by Padlina** [comment]
@janCstoffregen I fixed the CSS for the navigation menu (it is in the pull request for the branch "small-correction"). Regarding the user-friendliness of the search icon, I think it is ok (a lot of website have it like this) and I wouldn't know how to do it differently. If you have an idea I can do it. Otherwise I would close this issue.

**Comment by janCstoffregen** [comment]
solved
